# Generated by Django 4.2.16 on 2025-01-12 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('curr_address', models.TextField()),
                ('perm_address', models.TextField(null=True)),
                ('address_flag', models.BooleanField(default=False)),
                ('photo', models.ImageField(null=True, upload_to='profile-images')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A-Positive'), ('A-', 'A-Negative'), ('B+', 'B-Positive'), ('B-', 'B-Negative'), ('O+', 'O-Positive'), ('O-', 'O-Negative'), ('AB+', 'AB-Positive'), ('AB-', 'AB-Negative')], max_length=3, null=True)),
                ('celery_schedule', models.IntegerField(default=0)),
                ('e_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('student_permit', models.BooleanField(default=False)),
                ('company_permit', models.BooleanField(default=False)),
                ('placement_permit', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('contact_person', models.CharField(db_index=True, max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('abbr', models.CharField(db_index=True, max_length=20, unique=True)),
                ('duration', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('curr_address', models.TextField()),
                ('perm_address', models.TextField(null=True)),
                ('address_flag', models.BooleanField(default=False)),
                ('photo', models.ImageField(null=True, upload_to='profile-images')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A-Positive'), ('A-', 'A-Negative'), ('B+', 'B-Positive'), ('B-', 'B-Negative'), ('O+', 'O-Positive'), ('O-', 'O-Negative'), ('AB+', 'AB-Positive'), ('AB-', 'AB-Negative')], max_length=3, null=True)),
                ('celery_schedule', models.IntegerField(default=0)),
                ('roll_no', models.SlugField()),
                ('guardian_name', models.CharField(blank=True, max_length=255, null=True)),
                ('guardian_type', models.CharField(blank=True, choices=[('F', 'Father'), ('M', 'Mother'), ('G', 'Guradian')], max_length=1, null=True)),
                ('guardian_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('batch', models.IntegerField()),
                ('email', models.CharField(max_length=100, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('password_request_created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.TextField()),
                ('token_consumed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.admin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('activity', models.TextField(blank=True, null=True)),
                ('activity_type', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.admin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampusDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('drive_year', models.IntegerField()),
                ('package', models.CharField(db_index=True, max_length=10)),
                ('bond_period', models.IntegerField()),
                ('dateofdrive', models.DateField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Placements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('dateofjoining', models.DateField(blank=True, null=True)),
                ('campus_drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.campusdrive')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.student')),
            ],
            options={
                'unique_together': {('student', 'campus_drive')},
            },
        ),
    ]
