# Generated by Django 4.2.16 on 2025-01-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_alter_admin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
