# Generated by Django 4.2.16 on 2025-01-05 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0003_alter_campusdrive_id_alter_company_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='celery_schedule',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='perm_address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='student',
            name='celery_schedule',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='perm_address',
        ),
    ]
