# Generated by Django 4.2.16 on 2025-01-12 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('placement', '0003_alter_admin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_type',
            field=models.CharField(choices=[('F', 'Father'), ('M', 'Mother'), ('G', 'Guradian')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('blood_group', models.CharField(max_length=5)),
                ('student_permit', models.BooleanField(default=False)),
                ('placement_permit', models.BooleanField(default=False)),
                ('company_permit', models.BooleanField(default=False)),
                ('soft_delete', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.employee'),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.employee'),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
