# Generated by Django 4.2.16 on 2025-01-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0004_remove_employee_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A-Positive'), ('A-', 'A-Negative'), ('B+', 'B-Positive'), ('B-', 'B-Negative'), ('O+', 'O-Positive'), ('O-', 'O-Negative'), ('AB+', 'AB-Positive'), ('AB-', 'AB-Negative')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='celery_schedule',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='perm_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A-Positive'), ('A-', 'A-Negative'), ('B+', 'B-Positive'), ('B-', 'B-Negative'), ('O+', 'O-Positive'), ('O-', 'O-Negative'), ('AB+', 'AB-Positive'), ('AB-', 'AB-Negative')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='celery_schedule',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_type',
            field=models.CharField(blank=True, choices=[('F', 'Father'), ('M', 'Mother'), ('G', 'Guradian')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='perm_address',
            field=models.TextField(null=True),
        ),
    ]
