# Generated by Django 4.2.16 on 2025-01-14 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0004_alter_company_phone_alter_student_guardian_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAcademic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenth_percentage', models.FloatField()),
                ('twelfth_percentage', models.FloatField()),
                ('graduation_percentage', models.FloatField()),
                ('extra_courses', models.TextField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='placements',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='placements',
            constraint=models.UniqueConstraint(fields=('student', 'campus_drive'), name='unique_student_campus_drive'),
        ),
        migrations.AddField(
            model_name='studentacademic',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_info', to='placement.student'),
        ),
    ]
