# Generated by Django 4.2.16 on 2025-01-16 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('placement', '0005_studentacademic_alter_placements_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_type',
            field=models.CharField(choices=[('F', 'Father'), ('M', 'Mother'), ('G', 'Guardian')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.SlugField(unique=True),
        ),
    ]
