# Generated by Django 4.2.16 on 2025-01-07 18:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('placement', '0005_employee_blood_group_employee_celery_schedule_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Admin',
        ),
    ]
