# Generated by Django 4.2.16 on 2025-01-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0007_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
