# Generated by Django 4.2.16 on 2025-01-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0007_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='guardian_phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
