# Generated by Django 4.2.16 on 2025-01-08 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('placement', '0009_alter_admin_phone_alter_company_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_type',
            field=models.CharField(blank=True, choices=[('F', 'Father'), ('M', 'Mother'), ('G', 'Guardian')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
