# Generated by Django 4.2.16 on 2025-01-08 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0010_alter_admin_user_alter_student_guardian_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user',
            new_name='user1',
        ),
    ]
