# Generated by Django 4.2.16 on 2025-01-09 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0012_remove_student_user1_student_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user_id',
        ),
    ]
